# dependabot
# npm ライブラリは週一、GitHub Actions は月一でアップデートを調べる

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    groups:
      update-textlint:
        patterns:
          - "textlint"
          - "textlint-*"
          - "@textlint-ja/*"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule: 
      interval: "monthly"
    cooldown:
      default-days: 7
